// <auto-generated />
namespace ProjectWebSaleLand.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatecontext01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecontext01));
        
        string IMigrationMetadata.Id
        {
            get { return "201804020311227_update-context01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
